---
name: linter

on:
  push:
    branches:
      - master

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    permissions:
      contents: read
      packages: read

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: super linter
        uses: github/super-linter@v3
