---
name: linter

on:
  push:
    branches:
      - master

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: linter
        uses: github/super-linter@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          title: Code check
