---
name: linter

on:
  push:
    branches:
      - master

env:
  repo_token: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linter:
    name: linter
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: linter
        uses: github/super-linter@latest
        with:
          title: Code check
