---
name: "linter"

on:
  push:
    branches:
      - "master"

jobs:
  linter:
    name: "linter"
    runs-on: "ubuntu-latest"

    steps:
      # ...
      - name: "linter"
        uses: "github/super-linter@v1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: "Code check"
